### ISSUE TITLE
[bug]: Stream write after end

### ISSUE THREAD

**Issue by Izak88** [bleenco/abstruse#325]
Sometimes when multiple jobs are running at the same time, it happens that a writable stream is closed before the command has truly finished.

Error description:
```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:237:12)
    at Writable.write (_stream_writable.js:288:5)
    at IncomingMessage.<anonymous> (/home/izak/projects/abstruse/node_modules/docker-modem/lib/modem.js:301:16)
    at emitNone (events.js:115:13)
    at IncomingMessage.emit (events.js:218:7)
    at emitReadable_ (_stream_readable.js:516:10)
    at emitReadable (_stream_readable.js:510:7)
    at addChunk (_stream_readable.js:276:7)
    at readableAddChunk (_stream_readable.js:252:11)
    at IncomingMessage.Readable.push (_stream_readable.js:209:10)
    at HTTPParser.parserOnBody (_http_common.js:141:22)
    at Socket.socketOnData (_http_client.js:439:20)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
```

**Comment by irmana** [comment]
@jkuri is this issue still valid?
