### ISSUE TITLE
Runtime error when pulling image

### ISSUE THREAD

**Issue by MrCyjaneK** [bleenco/abstruse#488]
This issue occur only sometimes, but is causing tests to fail when pulling image

Here is full error:

```bash
abstruse@oldpc:~$ ./abstruse-worker.sh
2021-01-11T18:56:33.553+0100    INFO    grpc server listening on 0.0.0.0:3330   {"type": "server"}
2021-01-11T18:56:33.851+0100    INFO    connection with server successfully initialized {"type": "server"}
2021-01-11T18:56:35.943+0100    INFO    starting job 186 with name abstruse-job-186     {"type": "server"}
2021-01-11T18:56:36.022+0100    INFO    starting job 187 with name abstruse-job-187     {"type": "server"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x971375]

goroutine 55 [running]:
github.com/bleenco/abstruse/worker/docker.PullImage(0xc000035460, 0xd, 0xc0003d8090, 0x0, 0x0)
        /home/abstruse/abstruse/worker/docker/image.go:121 +0x215
github.com/bleenco/abstruse/worker/app.(*Server).StartJob(0xc0003c0230, 0xc000032500, 0xed7160, 0xc000064c80, 0x0, 0x0)
        /home/abstruse/abstruse/worker/app/server.go:211 +0xd18
github.com/bleenco/abstruse/pb._API_StartJob_Handler(0xd47780, 0xc0003c0230, 0xed61a0, 0xc000031dd0, 0xc00011d900, 0x0)
        /home/abstruse/abstruse/pb/api.pb.go:1115 +0x10b
github.com/bleenco/abstruse/worker/app.(*Server).streamInterceptor(0xc0003c0230, 0xd47780, 0xc0003c0230, 0xed4fa0, 0xc0001906c0, 0xc00011da40, 0xdfd538, 0xcbed01, 0xc00011da40)
        /home/abstruse/abstruse/worker/app/interceptor.go:63 +0x1cc
google.golang.org/grpc.(*Server).processStreamingRPC(0xc00044c1c0, 0xed8720, 0xc00046c480, 0xc000490d00, 0xc00042c3c0, 0x1381980, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.33.2/server.go:1464 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc00044c1c0, 0xed8720, 0xc00046c480, 0xc000490d00, 0x0)
        /root/go/pkg/mod/google.golang.org/grpc@v1.33.2/server.go:1537 +0xc9c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00042eb80, 0xc00044c1c0, 0xed8720, 0xc00046c480, 0xc000490d00)
        /root/go/pkg/mod/google.golang.org/grpc@v1.33.2/server.go:871 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /root/go/pkg/mod/google.golang.org/grpc@v1.33.2/server.go:869 +0x1fd
```

In the job log I can see:

```
==> Starting job 186 in abstruse-job-186...
==> Creating temp directory to mount volume... done
==> Cloning repository <my_private_repo> ref: refs/heads/master sha: 64e107fcbed7b17c8e7cbae14528d034616b61a0... done
==> Pulling image node:latest... 
==> rpc error: code = Unavailable desc = transport is closing
``` 

It is possible that I've lost network connection when the image was pulling.

**Comment by jkuri** [comment]
thanks for reporting this, I will check on it. yes you probably lost a connection but worker should not crash in any way.

**Comment by irmana** [comment]
@MrCyjaneK since this is a default Docker behavior when loosing connection there aren't too many ways how to fix this right. We may add a feature in Settings to setup the number of reconnect try-outs and the time in between... In case you have any other suggest feel free to drop us a note.

**Comment by MrCyjaneK** [comment]
For how I'm just starting abstruse worker in a while loop from my bash script. Anything that would wait few seconds and restart the worker will be fine.

**Comment by jkuri** [comment]
running in docker would do the trick, setting restart flag to always.
