### ISSUE TITLE
Possible bug in scheduler.go, splitting environment variables.

### ISSUE THREAD

**Issue by gbluma** [bleenco/abstruse#494]
It looks like the recent commit [5947f9d28ad10](https://github.com/bleenco/abstruse/commit/5947f9d28ad10a10ea234a5bd6f3ff3dcd742c1d#diff-6ba691086f6379e8fef43a9a8cc85930b010400d718a92257736e5a77a391b51R294) introduced a bug in `scheduler.go`.

When splitting the string for the environment variable, the length is not checked leading to an index-out-of-bounds error.

```
	var envs []*pb.EnvVariable
	env := strings.Split(job.Env, " ")
	for _, e := range env {
		splitted := strings.Split(e, "=")
		envs = append(envs, &pb.EnvVariable{
			Key:    splitted[0],
			Value:  splitted[1],              # <---- Line 294: Index 1 doesn't always exist in splitted
			Secret: false,
		})
	}
```

Here is the stderr output from my setup.

```  
panic: runtime error: index out of range [1] with length 1

goroutine 105 [running]:
github.com/bleenco/abstruse/server/scheduler.(*scheduler).startJob(0xc0000a0000, 0xc0005d4540, 0xc000187200)
	/app/server/scheduler/scheduler.go:294 +0x1757
created by github.com/bleenco/abstruse/server/scheduler.(*scheduler).process
	/app/server/scheduler/scheduler.go:262 +0x1f5
panic: runtime error: index out of range [1] with length 1

goroutine 26 [running]:
github.com/bleenco/abstruse/server/scheduler.(*scheduler).startJob(0xc0002f4000, 0xc003ca09c0, 0xc0002f3b00)
	/app/server/scheduler/scheduler.go:294 +0x1757
created by github.com/bleenco/abstruse/server/scheduler.(*scheduler).process
	/app/server/scheduler/scheduler.go:262 +0x1f5
panic: runtime error: index out of range [1] with length 1

goroutine 120 [running]:
github.com/bleenco/abstruse/server/scheduler.(*scheduler).startJob(0xc000442090, 0xc000448000, 0xc0004a9680)
	/app/server/scheduler/scheduler.go:294 +0x1757
created by github.com/bleenco/abstruse/server/scheduler.(*scheduler).process
	/app/server/scheduler/scheduler.go:262 +0x1f5
```

I might try to follow-up with a pull request, but I don't have a dev setup configured at the moment.

**Comment by jkuri** [comment]
fixed with https://github.com/bleenco/abstruse/pull/495
